### ISSUE TITLE
Not appearing in Steam pages

### ISSUE THREAD

**Issue by rmenessec** [DanielKamkha/GameDeals#1]
As of this writing, I'm not seeing any additional pricing from the addon appearing in Steam pages. I'm using Greasemonkey with:
- https://openuserjs.org/scripts/rmenessec/Steam_DRM_Highlighter_Revenant/
- https://openuserjs.org/scripts/Mr_McPowned/Steam_Linkfilter_Redirector_(linkredirector)
- https://greasyfork.org/en/scripts/391-steam-overall-enhancement-ue

**Comment by DanielKamkha** [comment]
Not reproducible with just GameDeals and no other add-ons. So has to be a compatibility issue with one of your usescripts. I'm looking into the issue.

**Comment by DanielKamkha** [comment]
Compatibility issue with https://greasyfork.org/en/scripts/391-steam-overall-enhancement-ue.

**Comment by DanielKamkha** [comment]
Tested with Greasmonkey and all three userscripts installed, FF44. GameDeals still works fine. Not reproducible.
