### ISSUE TITLE
Addon icon size not compatible with Classic Theme Restorer

### ISSUE THREAD

**Issue by rmenessec** [DanielKamkha/GameDeals#2]
I generally use Classic Theme Restorer with metrics selected to best fit 16x16px icons. The GameDeals addon bar icon appears to be somewhere around 20x20 or 22x22px at the lowest; at this size, selecting the option to show the icon in the Firefox URL bar throws off the metrics and forces the URL bar (and the entire toolbar) to jump in size.

If you could add a 16x16px version of the icon, it would be greatly appreciated. Also, would you consider making the addon icon normally selectable from the Firefox "customize" view, so that the icon can be placed anywhere in the browser chrome?

Thanks!

**Comment by DanielKamkha** [comment]
I have done a small feasibility study on providing 16x16 icon for the urlbar button. Looks like determining the current size of the URLBar in Firefox is too much of a hassle. So not doing this for now.

I'm planning to migrate GameDeals to WebExtensions API when it gets full support in FF. Maybe it will be easier to do by then.

As for the customization button, that's a good idea. I've added it to the list of future improvements for GameDeals.
