### ISSUE TITLE
Why was the extension removed from both Chrome and Firefox?

### ISSUE THREAD

**Issue by RubbelDieKatz** [DanielKamkha/GameDeals#4]
Both links in the readme go to a 404 page, with Firefox saying that the extension "was removed by its author".

**Comment by DanielKamkha** [comment]
The extension proved to be unpopular while requiring a considerable effort to keep up-to-date with the constant changes to targeted web sites. Thus it has been discontinued. Feel free to re-use any parts from it, if you want to. However, I'd recommend against it. isthereanydeal API has changed in the mean time, to the old might not work at all.
